import React from 'react';
import classNames from 'classnames';

const links = {
  Github: 'https://github.com/joesmith100',
  Codepen: 'http://codepen.io/joesmith/',
  Linkedin: 'https://uk.linkedin.com/in/joe-smith-42b06749',
  Facebook: 'https://www.facebook.com/joesmith04',
  Email: 'mailto:joesmith0488@gmail.com'
};

function Footer({ footerVisible, contentActive }) {
  return (
    <footer className={classNames({
        'Footer': true,
        'Footer--content-active': contentActive,
      })}>
      <section className={classNames({
          'Footer__wrapper': true,
          'Footer__wrapper--visible': footerVisible || contentActive,
        })}>
        {Object.keys(links).map(link => (
          <a key={link} href={links[link]} target="_blank">
            <i className={`Footer__wrapper__icon Footer__wrapper__icon--${link}`} />
          </a>
        ))}
        <p className="Footer__wrapper__attribution">
          Icons generated by <a href="http://www.flaticon.com">flaticon.com</a>.
        </p>
        <secion className="Footer__wrapper__copyright">© 2016 Joe Smith</secion>
      </section>
    </footer>
  );
}

export default Footer;
